version: "3.9"

services:
  circuitlab-backend:
    build:
      context: /volume1/docker/circuitlab/backend
      network: host
    container_name: circuitlab-backend
    restart: unless-stopped
    network_mode: host
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - /volume1/docker/circuitlab/backend/data:/app/data

  circuitlab-ui:
    image: nginx:alpine
    container_name: circuitlab-ui
    restart: unless-stopped
    network_mode: host
    depends_on:
      - circuitlab-backend
    volumes:
      - /volume1/docker/circuitlab/web:/usr/share/nginx/html:ro
      - /volume1/docker/circuitlab/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
